---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: loki-operator
      namespace: openshift-operators-redhat
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
